# Generated by Django 4.0.1 on 2022-02-23 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DlObjects',
            fields=[
                ('objectid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('object_label', models.CharField(blank=True, max_length=200, null=True)),
                ('object_level', models.IntegerField()),
            ],
            options={
                'db_table': 'dl_objects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DlObjectTypes',
            fields=[
                ('object_typeid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'dl_object_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=200)),
                ('project_manager', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('working_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('webapp_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('image_masters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('image_submasters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('audio_masters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('audio_submasters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('video_masters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('video_submasters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('text_masters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('text_submasters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('setup_flag', models.CharField(max_length=3)),
                ('auto_publish_flag', models.CharField(max_length=3)),
                ('lob_masters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('lob_submasters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('dpr_access_groupid', models.CharField(blank=True, max_length=30, null=True)),
                ('webapp_name', models.CharField(max_length=30, unique=True)),
                ('thumbnail_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('item_ordering_flag', models.CharField(blank=True, max_length=3, null=True)),
                ('website_masters_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('oai_flag', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QaStatus',
            fields=[
                ('statusid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'qa_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectItems',
            fields=[
                ('divid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateField()),
                ('last_edit_date', models.DateField()),
                ('item_ark', models.CharField(max_length=500, unique=True)),
                ('sent_to_dpr_flag', models.CharField(blank=True, max_length=3, null=True)),
                ('parent_divid', models.IntegerField(blank=True, null=True)),
                ('item_sequence', models.IntegerField(blank=True, null=True)),
                ('desc_clob', models.TextField(blank=True, null=True)),
                ('old_divid', models.CharField(blank=True, max_length=100, null=True)),
                ('old_parent_divid', models.CharField(blank=True, max_length=100, null=True)),
                ('node_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=30, null=True)),
                ('objectid_fk', models.ForeignKey(db_column='objectid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.dlobjects')),
                ('projectid_fk', models.ForeignKey(db_column='projectid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.projects')),
                ('statusid_fk', models.ForeignKey(blank=True, db_column='statusid_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='oral_history.qastatus')),
            ],
            options={
                'db_table': 'project_items',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='dlobjects',
            name='object_typeid_fk',
            field=models.ForeignKey(db_column='object_typeid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.dlobjecttypes'),
        ),
        migrations.AddField(
            model_name='dlobjects',
            name='projectid_fk',
            field=models.ForeignKey(db_column='projectid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.projects'),
        ),
    ]
