# Generated by Django 4.0.1 on 2022-05-17 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroups',
            fields=[
                ('file_groupid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('file_group_title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('projectid_fk', models.ForeignKey(db_column='projectid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.projects')),
            ],
            options={
                'db_table': 'file_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContentFiles',
            fields=[
                ('fileid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('mime_type', models.CharField(blank=True, max_length=75, null=True)),
                ('file_sequence', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('file_location', models.CharField(blank=True, max_length=500, null=True)),
                ('location_type', models.CharField(blank=True, max_length=25, null=True)),
                ('file_use', models.CharField(blank=True, max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(blank=True, max_length=25, null=True)),
                ('old_fileid', models.CharField(blank=True, max_length=100, null=True)),
                ('bfile_video', models.TextField(blank=True, null=True)),
                ('blob_video', models.TextField(blank=True, null=True)),
                ('clob_text', models.TextField(blank=True, null=True)),
                ('nclob_text', models.TextField(blank=True, null=True)),
                ('bfile_image', models.TextField(blank=True, null=True)),
                ('blob_image', models.TextField(blank=True, null=True)),
                ('bfile_audio', models.TextField(blank=True, null=True)),
                ('blob_audio', models.TextField(blank=True, null=True)),
                ('bfile_lob', models.TextField(blank=True, null=True)),
                ('blob_lob', models.BinaryField(blank=True, null=True)),
                ('divid_fk', models.ForeignKey(db_column='divid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.projectitems')),
                ('file_groupid_fk', models.ForeignKey(db_column='file_groupid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.filegroups')),
            ],
            options={
                'db_table': 'content_files',
                'managed': True,
            },
        ),
    ]
