# Generated by Django 4.0.1 on 2022-05-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '003_add_verbose_plurals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminControlValues',
            fields=[
                ('admin_cvid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_cv', models.CharField(max_length=500)),
                ('admin_cv_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'admin_control_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminGroups',
            fields=[
                ('admin_groupid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_group_title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'admin_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminQualifiers',
            fields=[
                ('admin_qualifierid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_qualifier', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifier_term_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_qualifiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminTerms',
            fields=[
                ('admin_termid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_term', models.CharField(max_length=100)),
                ('control_value_flag', models.CharField(blank=True, max_length=3, null=True)),
                ('qualifier_flag', models.CharField(blank=True, max_length=3, null=True)),
                ('repeat_flag', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'admin_terms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminTypes',
            fields=[
                ('admin_typeid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_type', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'admin_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminValues',
            fields=[
                ('admin_valueid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_value', models.CharField(blank=True, max_length=3000, null=True)),
                ('admin_profile', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkAdminGroups',
            fields=[
                ('admin_linkid_pk', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'link_admin_groups',
                'managed': False,
            },
        ),
    ]
