# Generated by Django 4.0.1 on 2022-05-27 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '003_add_verbose_plurals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminControlValues',
            fields=[
                ('admin_cvid_pk', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_cv', models.CharField(max_length=500)),
                ('admin_cv_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'admin_control_values',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminGroups',
            fields=[
                ('admin_groupid_pk', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_group_title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'admin_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminQualifiers',
            fields=[
                ('admin_qualifierid_pk', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_qualifier', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifier_term_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_qualifiers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminTerms',
            fields=[
                ('admin_termid_pk', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_term', models.CharField(max_length=100)),
                ('control_value_flag', models.CharField(blank=True, max_length=3, null=True)),
                ('qualifier_flag', models.CharField(blank=True, max_length=3, null=True)),
                ('repeat_flag', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'admin_terms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminTypes',
            fields=[
                ('admin_typeid_pk', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_type', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'admin_types',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='contentfiles',
            name='fileid_pk',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filegroups',
            name='file_groupid_pk',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LinkAdminGroups',
            fields=[
                ('admin_linkid_pk', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_groupid_fk', models.ForeignKey(blank=True, db_column='admin_groupid_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='oral_history.admingroups')),
                ('file_groupid_fk', models.ForeignKey(blank=True, db_column='file_groupid_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='oral_history.filegroups')),
            ],
            options={
                'db_table': 'link_admin_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminValues',
            fields=[
                ('admin_valueid_pk', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_value', models.CharField(blank=True, max_length=2000, null=True)),
                ('admin_profile', models.TextField(blank=True, null=True)),
                ('admin_cvid_fk', models.ForeignKey(blank=True, db_column='admin_cvid_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='oral_history.admincontrolvalues')),
                ('admin_groupid_fk', models.ForeignKey(db_column='admin_groupid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.admingroups')),
                ('admin_qualifierid_fk', models.ForeignKey(blank=True, db_column='admin_qualifierid_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='oral_history.adminqualifiers')),
                ('admin_termid_fk', models.ForeignKey(db_column='admin_termid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.adminterms')),
            ],
            options={
                'db_table': 'admin_values',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='adminterms',
            name='admin_typeid_fk',
            field=models.ForeignKey(db_column='admin_typeid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.admintypes'),
        ),
        migrations.AddField(
            model_name='adminqualifiers',
            name='admin_termid_fk',
            field=models.ForeignKey(blank=True, db_column='admin_termid_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='oral_history.adminterms'),
        ),
        migrations.AddField(
            model_name='admingroups',
            name='admin_typeid_fk',
            field=models.ForeignKey(db_column='admin_typeid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.admintypes'),
        ),
        migrations.AddField(
            model_name='admincontrolvalues',
            name='admin_termid_fk',
            field=models.ForeignKey(db_column='admin_termid_fk', on_delete=django.db.models.deletion.CASCADE, to='oral_history.adminterms'),
        ),
    ]
