# Generated by Django 4.0.1 on 2022-06-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '0004_admincontrolvalues_admingroups_adminqualifiers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentfiles',
            name='bfile_audio',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='bfile_image',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='bfile_lob',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='bfile_video',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='blob_audio',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='blob_image',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='blob_lob',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='blob_video',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='clob_text',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='nclob_text',
        ),
        migrations.RemoveField(
            model_name='contentfiles',
            name='old_fileid',
        ),
    ]
