# Generated by Django 4.0.1 on 2022-05-17 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oral_history', '0002_filegroups_contentfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentfiles',
            options={'managed': True, 'verbose_name_plural': 'content files'},
        ),
        migrations.AlterModelOptions(
            name='filegroups',
            options={'managed': True, 'verbose_name_plural': 'file groups'},
        ),
        migrations.AlterModelOptions(
            name='projectitems',
            options={'managed': True, 'verbose_name_plural': 'project items'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'managed': True, 'verbose_name_plural': 'projects'},
        ),
    ]
