apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dlcs-staff-ui.fullname" . }}-configmap
  namespace: dlcs-staff-ui{{ .Values.django.env.run_env }}
  labels:
    {{- include "dlcs-staff-ui.labels" . | nindent 4 }}
data:
  DJANGO_RUN_ENV: {{ .Values.django.env.run_env }}
  DJANGO_DEBUG: {{ .Values.django.env.debug | quote }}
  DJANGO_ALLOWED_HOSTS: {{ range .Values.django.env.allowed_hosts }}{{ . | quote }}{{ end }}
  DJANGO_DB_DSN: {{ .Values.django.env.db_dsn }}
  DJANGO_DB_USER: {{ .Values.django.env.db_user }}
  DJANGO_DLCS_FILE_SOURCE: {{ .Values.django.env.dlcs_file_source }}
  DJANGO_OH_LIBPARTNERS: {{ .Values.django.env.oh_libpartners }}
  DJANGO_OH_MASTERSLZ: {{ .Values.django.env.oh_masterslz }}
  # oh_static is not yet mounted: https://jira.library.ucla.edu/browse/SYS-862
  #DJANGO_OH_STATIC: {{ .Values.django.env.oh_static }}
  DJANGO_OH_WOWZA: {{ .Values.django.env.oh_wowza }}
