apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "dlcs-staff-ui.fullname" . }}-pv-ohsource
spec:
  capacity:
    storage: {{ .Values.persistentVolumes.ohsource.storage | quote }}
  accessModes:
    - {{ .Values.persistentVolumes.ohsource.access }}
  nfs:
    server: {{ .Values.persistentVolumes.ohsource.server | quote }}
    path: "/"
  mountOptions:
    - nfsvers=3