apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dlcs-staff-ui.fullname" . }}-pvc-ohmasters
  namespace: dlcs-staff-ui{{ .Values.django.env.run_env }}
spec:
  accessModes:
    - {{ .Values.persistentVolumes.ohmasters.access }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistentVolumes.ohmasters.storage }}
  volumeName: {{ include "dlcs-staff-ui.fullname" . }}-pv-ohmasters