apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dlcs-staff-ui.fullname" . }}-pvc-ohsource
  namespace: dlcs-staff-ui{{ .Values.django.env.run_env }}
spec:
  accessModes:
    - {{ .Values.persistentVolumes.ohsource.access }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistentVolumes.ohsource.storage }}
  volumeName: {{ include "dlcs-staff-ui.fullname" . }}-pv-ohsource