apiVersion: v1
kind: Service
metadata:
  name: {{ include "dlcs-staff-ui.fullname" . }}
  namespace: dlcs-staff-ui{{ .Values.django.env.run_env }}
  labels:
    {{- include "dlcs-staff-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.django.env.target_port | default "8000" }}
      protocol: TCP
      name: http
  selector:
    {{- include "dlcs-staff-ui.selectorLabels" . | nindent 4 }}
